stages:
  - test

install_and_test:
  stage: test
  image: node:22 # Use Node.js version 22 image
  variables:
    CODECOV_TOKEN: $CODECOV_TOKEN
  before_script:
    - apt-get update && apt-get install -y python3 python3-pip
    - pip3 install codecov-cli
  script:
    - npm install # Install dependencies
    - npx vitest run --coverage # Run tests with Vitest and generate coverage
  after_script:
    - ./codecov --token $CODECOV_TOKEN --url https://codecov.mycs.zone
