on:
  push:
    branches:
      - master
jobs:
  installtest:
    name: Install and Test with Coverage
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run test:coverage
